### ISSUE TITLE
Cannot Set Initial Date

### ISSUE THREAD

**Issue by okputadora** [react-native-community/datetimepicker#110] opened 2020-02-04 21:45 UTC
@vonovak It seems that the date picker cannot be set to an initial date. It always opens to todays date and ignores the value passed to `value`. Is this the intended behavior?

Thanks in advance for any help you might be able to provide

**Comment by vonovak** [comment] 2020-02-04 22:03
hi and thanks for asking. Can you provide a code snippet? What platform is this on? thanks.

**Comment by lobster00** [comment] 2020-02-07 17:04
for me it works with ios but on android the datetimepicker always sets the date to the current date

**Comment by jackfiallos** [comment] 2020-02-12 11:48
hey guys, I noticed this before and seeing the code I have a question

why a new Date() is used here instead of using pre-defined value?

```javascript
// @react-native-community/datetimepicker/src/datetimepicker.android.js
picker.then(
    function resolve({action, day, month, year, minute, hour}) {
      const date = new Date(); <-- here 😕 
      ...
  );
```

I started the component with value eg. 2020-02-13 but when onChange event is triggered returns 2020-02-12, happening on Android with timepicker only.

**Comment by azor0** [comment] 2020-02-19 10:20
I have the same problem

**Comment by salmanitb** [comment] 2020-02-21 11:58
@jackfiallos use moment..
moment.utc(date).local().format('MM/DD/YYYY')
and its work for me

**Comment by jackfiallos** [comment] 2020-02-21 12:07
> @jackfiallos use moment..
> moment.utc(date).local().format('MM/DD/YYYY')
> and its work for me

Hi @salmanitb, I think that's not gonna fix the problem because is not a formatting issue, in fact the issue is with the date object.

Anyone can confirm this? or it's me doing something silly.

**Comment by nataly-chobat** [comment] 2020-03-04 08:08
Hello @jackfiallos, faced the same issue on android :(

`"@react-native-community/datetimepicker": "^2.2.2",`
`"react-native": "0.61.5",`

**Comment by nataly-chobat** [comment] 2020-03-04 09:06
The reason was in missing updates. Solved by adding
```
useEffect(() => {
        if (!isIOS) {
            setSelectedDate(date)
        }
    }, [date])
```
to my component `DatePickerModal` which renders `DateTimePicker` and receives `date` as a prop

**Comment by jackfiallos** [comment] 2020-03-04 09:23
Thanks @nataly-chobat, I've solve this differently but gonna update and see how the new patch works, I saw the code changed after my suggestion.

**Comment by alexsthub** [comment] 2020-03-16 03:32
Hi @nataly-chobat, I don't really understand your solution. Do you think you could help me out with the problem without using hooks? @jackfiallos if you found a different solution could you share that? Thank you! 
 
`constructor(props) {
    super(props);
    this.state = {
      selectedDate: moment(),
    };
  }

datepickerSelect = date => {
    const d = moment(date);
    this.setState({modalVisible: false, selectedDate: d});
  };

<DateTimePickerModal
          isVisible={this.state.modalVisible}
          mode="date"
          minimumDate={new Date()}
          value={this.state.selectedDate.toDate()}
          onConfirm={this.datepickerSelect}
          onCancel={() => this.setState({modalVisible: false})}
        />
`

**Comment by GennadiiFairushin** [comment] 2020-03-26 10:58
Hi guys, is not it fixed?

https://github.com/react-native-community/datetimepicker/commit/1871168d1bb4073b42455e9a03188654d7234321

https://github.com/react-native-community/datetimepicker/issues/94

**Comment by AVATAR197** [comment] 2020-04-13 16:26
I have the same problem... probably it's not fixed yet. I am using mmazzarolo/react-native-modal-datetime-picker which uses this library. Do you guys have some other solutions?

**Comment by vonovak** [comment] 2020-05-28 22:27
This should be fixed by https://github.com/react-native-community/datetimepicker/commit/1871168d1bb4073b42455e9a03188654d7234321

If you're still experiencing this, please open a new issue and follow the issue template, thanks!

**Closed by vonovak** 2020-05-28 22:27 UTC
