### ISSUE TITLE
Time picker shows AM AM

### ISSUE THREAD

**Issue by jc-gm** [react-native-community/datetimepicker#51] opened 2019-11-04 03:20 UTC
# Bug
I noticed a bug with the time picker, where it shows AM AM instead of AM PM.  This only happened today (Nov 3th), when we had the switch from EDT to EST.  I manually changed the device date to Nov 4th and it went back to displaying AM PM. 
This is the code I'm using:

<DatePicker
                    style={Styles.datePickerStyle}
                    date={date}
                    mode="time"
                    format="hh:mm A"
                    onDateChange={(date) => this.handleDateTime(date)}
                />

Am I doing something wrong? or is this a bug?

![Screenshot_20191103-110659_eDiary](https://user-images.githubusercontent.com/22181421/68097980-0ab2ad00-fe88-11e9-88cc-02afaa1deb78.jpg)

Library version: 2.7.0

**Comment by vonovak** [comment] 2020-03-20 23:20
hello, thanks for reporting. It's quite possible that this is a bug. If that is the case, it's not a bug in our code but apple's implementation. Because we cannot really do anything about this, I'm closing this. Thanks!

**Closed by vonovak** 2020-03-20 23:20 UTC
