### ISSUE TITLE
Done button is missing after choosing the date in ios platform.

### ISSUE THREAD

**Issue by anshumanburman** [react-native-community/datetimepicker#212] opened 2020-07-04 06:23 UTC
this library is working fine in both platform and android datepicker has (ok, cancel) button to dismiss the datepicker after selection the date but it is missing in ios version only presenting datepicker but there is no any option to dismiss the date picker after choosing the date. please add this functionality in this library asap.

**Comment by vonovak** [comment] 2020-07-07 22:06
hello, I'm closing this as duplicate of https://github.com/react-native-community/datetimepicker/issues/214

**Closed by vonovak** 2020-07-07 22:06 UTC
