### ISSUE TITLE
Changing basic color on Android 

### ISSUE THREAD

**Issue by rom529** [react-native-community/datetimepicker#149] opened 2020-04-13 18:31 UTC
# Question
How can I change the basic color in the background of the date and the time picker?

**Comment by hxqbeyond** [comment] 2020-04-14 03:38
same issues,need change basic color.

**Comment by whizsid** [comment] 2020-04-15 12:58
Duplicate of #20

**Comment by vonovak** [comment] 2020-04-15 13:24
hello, thanks for reporting, I'm closing this as duplicate ^.

**Closed by vonovak** 2020-04-15 13:24 UTC
