### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNDateTimePicker" was not found in the UIManager

### ISSUE THREAD

**Issue by hengvenchang** [react-native-community/datetimepicker#70] opened 2019-12-24 07:52 UTC
When i run "react-native run-ios"! the component seems to work just fine!
But when i run "detox test", i got this error:

Invariant Violation: requireNativeComponent: "RNDateTimePicker" was not found in the UIManager

Is this plugin not usable with detox?

**Comment by joecervino** [comment] 2020-01-13 16:57
+1

**Comment by LukeXF** [comment] 2020-01-20 17:15
+1

**Comment by rafaelcavalcante** [comment] 2020-01-21 17:34
Duplicated from #12

**Comment by vonovak** [comment] 2020-03-20 00:47
hello, this is most likely problem with linking the module. I'm closing this because there is no runnable reproduction. 

please create a new issue with repro and we'll be happy to review it!

**Closed by vonovak** 2020-03-20 00:47 UTC
